site_name: LiHuaMao 的小站
site_url: https://lihuamao.github.io/

nav:
  - Home: index.md
  - Blog:
     - blog/index.md
  - Flow Matching:
     - FlowMatching/index.md
     - FlowMatching/FlowMatching.md
     - FlowMatching/ConsistencyModel.md
  - 面经整理:
     - interview/index.md
     - interview/algorithm.md
  - 关于我: about.md

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.indexes
    - navigation.tabs       # 启用顶部标签页
    - navigation.sections   # 启用导航分组
    - navigation.expand     # 展开导航项
    - navigation.top        # 返回顶部按钮
plugins:
  - search
  - blog

extra_css:
  - stylesheets/extra.css