site_name: LiHuaMao 的小站
site_url: https://lihuamao.github.io/

nav:
  - Home: 
     - index.md
     - tags.md
  - Blog:
     - blog/index.md
  - Diffusion Model:
     - DiffusionModel/index.md
     - DiffusionModel/FlowMatching.md
     - DiffusionModel/ConsistencyModel.md
     - DiffusionModel/RectifiedFlow.md
     - DiffusionModel/DistributionMatching.md
     - DiffusionModel/UnderstandingDiffusionModels.md
     - DiffusionModel/Diff-Instruct.md
     - DiffusionModel/DreamDiffusion.md
     - DiffusionModel/MeanFlow.md
     - DiffusionModel/SelfDistillation.md
  - 经验贴整理:
     - experience/index.md
     - experience/algorithm.md
     - experience/cc98.md
     - experience/softwareEngineer.md
     - experience/resources.md
     - experience/others.md
  - 模型后训练:
     - PostTraining/RLHF.md
  - 课程笔记:
    - UML建模:
      - UML/index.md
      - UML/UseCaseDiagram.md
      - UML/SequenceDiagram.md
      - UML/CommunicationDiagram.md
    - 计算机系统原理:
      - ComputerOrganization/chapter1.md
      - ComputerOrganization/chapter2.md
      - ComputerOrganization/chapter3.md
      - ComputerOrganization/chapter4.md
  - 关于我: about.md

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.indexes
    - navigation.tabs       # 启用顶部标签页
    - navigation.sections   # 启用导航分组
    # - navigation.expand     # 展开导航项(注释掉以启用折叠功能)
    - navigation.top        # 返回顶部按钮
    - content.code.annotate # 代码注释
    - content.code.copy     # 代码复制按钮
plugins:
  - search
  - blog
  - callouts
  - tags:
      tags_file: tags.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - javascripts/katex.js